-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 21:34:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `mydb`.`tbl_tipoDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_tipoDocumento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_tipoDocumento` (
  `des_tipoDocumento` VARCHAR(5) NOT NULL,
  `lugarExpedicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`des_tipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_observaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_observaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_observaciones` (
  `tipoObservacion` VARCHAR(15) NOT NULL,
  `des_observacion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`tipoObservacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_persona` (
  `numeroDocumento` VARCHAR(12) NOT NULL,
  `nombre1` VARCHAR(30) NOT NULL,
  `nombre2` VARCHAR(30) NULL,
  `apellido1` VARCHAR(30) NOT NULL,
  `apellido2` VARCHAR(30) NULL,
  `lugarNacimiento` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `tbl_tipoDocumento_des_tipoDocumento` VARCHAR(5) NOT NULL,
  `tbl_observaciones_tipoObservacion` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`numeroDocumento`, `tbl_tipoDocumento_des_tipoDocumento`),
  INDEX `fk_tbl_persona_tbl_tipoDocumento1_idx` (`tbl_tipoDocumento_des_tipoDocumento` ASC) VISIBLE,
  INDEX `fk_tbl_persona_tbl_observaciones1_idx` (`tbl_observaciones_tipoObservacion` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_persona_tbl_tipoDocumento1`
    FOREIGN KEY (`tbl_tipoDocumento_des_tipoDocumento`)
    REFERENCES `mydb`.`tbl_tipoDocumento` (`des_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_persona_tbl_observaciones1`
    FOREIGN KEY (`tbl_observaciones_tipoObservacion`)
    REFERENCES `mydb`.`tbl_observaciones` (`tipoObservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_rh`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_rh` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_rh` (
  `des_rh` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`des_rh`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_eps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_eps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_eps` (
  `des_eps` VARCHAR(30) NOT NULL,
  `estrato` INT NOT NULL,
  PRIMARY KEY (`des_eps`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_teléfono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_teléfono` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_teléfono` (
  `clase` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`clase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_pagoMes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_pagoMes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_pagoMes` (
  `numeroComprobante` VARCHAR(30) NOT NULL,
  `formaPago` VARCHAR(15) NOT NULL,
  `fechaPago` DATE NOT NULL,
  `mesCancelado` VARCHAR(30) NOT NULL,
  `responsableColegio` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`numeroComprobante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_matricula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `curso` INT NOT NULL,
  `fechaInicial` DATE NOT NULL,
  `fechaFinal` DATE NULL,
  `estado` TINYINT NOT NULL,
  `grado` VARCHAR(15) NULL,
  PRIMARY KEY (`id_matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_estudiante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_estudiante` (
  `tbl_matricula_id_matricula` INT NOT NULL,
  `tbl_persona_numeroDocumento` VARCHAR(12) NOT NULL,
  `tbl_persona_tbl_tipoDocumento_des_tipoDocumento` VARCHAR(5) NOT NULL,
  `tbl_eps_des_eps` VARCHAR(30) NOT NULL,
  `tbl_rh_des_rh` VARCHAR(50) NOT NULL,
  INDEX `fk_tbl_estudiante_tbl_matricula1_idx` (`tbl_matricula_id_matricula` ASC) VISIBLE,
  PRIMARY KEY (`tbl_persona_numeroDocumento`, `tbl_persona_tbl_tipoDocumento_des_tipoDocumento`),
  INDEX `fk_tbl_estudiante_tbl_eps1_idx` (`tbl_eps_des_eps` ASC) VISIBLE,
  INDEX `fk_tbl_estudiante_tbl_rh1_idx` (`tbl_rh_des_rh` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_estudiante_tbl_matricula1`
    FOREIGN KEY (`tbl_matricula_id_matricula`)
    REFERENCES `mydb`.`tbl_matricula` (`id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_estudiante_tbl_persona1`
    FOREIGN KEY (`tbl_persona_numeroDocumento` , `tbl_persona_tbl_tipoDocumento_des_tipoDocumento`)
    REFERENCES `mydb`.`tbl_persona` (`numeroDocumento` , `tbl_tipoDocumento_des_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_estudiante_tbl_eps1`
    FOREIGN KEY (`tbl_eps_des_eps`)
    REFERENCES `mydb`.`tbl_eps` (`des_eps`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_estudiante_tbl_rh1`
    FOREIGN KEY (`tbl_rh_des_rh`)
    REFERENCES `mydb`.`tbl_rh` (`des_rh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_parentesco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_parentesco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_parentesco` (
  `des_parentesco` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`des_parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_responsable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_responsable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_responsable` (
  `ocupacion` VARCHAR(35) NOT NULL,
  `profesion` VARCHAR(35) NOT NULL,
  `tbl_persona_numeroDocumento` VARCHAR(12) NOT NULL,
  `tbl_persona_tbl_tipoDocumento_des_tipoDocumento` VARCHAR(5) NOT NULL,
  `tbl_parentesco_des_parentesco` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`tbl_persona_numeroDocumento`, `tbl_persona_tbl_tipoDocumento_des_tipoDocumento`),
  INDEX `fk_tbl_responsable_tbl_parentesco1_idx` (`tbl_parentesco_des_parentesco` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_responsable_tbl_persona1`
    FOREIGN KEY (`tbl_persona_numeroDocumento` , `tbl_persona_tbl_tipoDocumento_des_tipoDocumento`)
    REFERENCES `mydb`.`tbl_persona` (`numeroDocumento` , `tbl_tipoDocumento_des_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_responsable_tbl_parentesco1`
    FOREIGN KEY (`tbl_parentesco_des_parentesco`)
    REFERENCES `mydb`.`tbl_parentesco` (`des_parentesco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_matricula_has_tbl_pagoMes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_matricula_has_tbl_pagoMes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_matricula_has_tbl_pagoMes` (
  `tbl_matricula_id_matricula` INT NOT NULL,
  `tbl_pagoMes_numeroComprobante` VARCHAR(30) NOT NULL,
  `mes` VARCHAR(15) NOT NULL,
  `valorCancelado` FLOAT NOT NULL,
  `saldo` FLOAT NOT NULL,
  PRIMARY KEY (`tbl_matricula_id_matricula`, `tbl_pagoMes_numeroComprobante`),
  INDEX `fk_tbl_matricula_has_tbl_pagoMes_tbl_pagoMes1_idx` (`tbl_pagoMes_numeroComprobante` ASC) VISIBLE,
  INDEX `fk_tbl_matricula_has_tbl_pagoMes_tbl_matricula1_idx` (`tbl_matricula_id_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_matricula_has_tbl_pagoMes_tbl_matricula1`
    FOREIGN KEY (`tbl_matricula_id_matricula`)
    REFERENCES `mydb`.`tbl_matricula` (`id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_has_tbl_pagoMes_tbl_pagoMes1`
    FOREIGN KEY (`tbl_pagoMes_numeroComprobante`)
    REFERENCES `mydb`.`tbl_pagoMes` (`numeroComprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_persona_has_tbl_teléfono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tbl_persona_has_tbl_teléfono` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tbl_persona_has_tbl_teléfono` (
  `tbl_persona_numeroDocumento` VARCHAR(12) NOT NULL,
  `tbl_persona_tbl_tipoDocumento_des_tipoDocumento` VARCHAR(5) NOT NULL,
  `tbl_teléfono_clase` VARCHAR(15) NOT NULL,
  `numero` INT(15) NOT NULL,
  PRIMARY KEY (`tbl_persona_numeroDocumento`, `tbl_persona_tbl_tipoDocumento_des_tipoDocumento`, `tbl_teléfono_clase`),
  INDEX `fk_tbl_persona_has_tbl_teléfono_tbl_teléfono1_idx` (`tbl_teléfono_clase` ASC) VISIBLE,
  INDEX `fk_tbl_persona_has_tbl_teléfono_tbl_persona1_idx` (`tbl_persona_numeroDocumento` ASC, `tbl_persona_tbl_tipoDocumento_des_tipoDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_persona_has_tbl_teléfono_tbl_persona1`
    FOREIGN KEY (`tbl_persona_numeroDocumento` , `tbl_persona_tbl_tipoDocumento_des_tipoDocumento`)
    REFERENCES `mydb`.`tbl_persona` (`numeroDocumento` , `tbl_tipoDocumento_des_tipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_persona_has_tbl_teléfono_tbl_teléfono1`
    FOREIGN KEY (`tbl_teléfono_clase`)
    REFERENCES `mydb`.`tbl_teléfono` (`clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
