-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 11:34:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `proyecto`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_users_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `proyecto`.`rol` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `proyecto`.`tipos_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`tipos_documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion_tdoc` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `proyecto`.`observaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`observaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `des_observacion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `proyecto`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ndoc` VARCHAR(12) NOT NULL,
  `tdoc_persona` INT NOT NULL,
  `tipo_persona` VARCHAR(45) NOT NULL,
  `nombre1` VARCHAR(30) NOT NULL,
  `nombre2` VARCHAR(30) NULL DEFAULT NULL,
  `apellido1` VARCHAR(30) NOT NULL,
  `apellido2` VARCHAR(30) NULL DEFAULT NULL,
  `lugar_expedicion` VARCHAR(45) NOT NULL,
  `lugar_nacimiento` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `id_observacion` INT NULL DEFAULT NULL,
  `tel1` VARCHAR(12) NOT NULL,
  `tel2` VARCHAR(12) NULL DEFAULT NULL,
  `tel3` VARCHAR(12) NULL DEFAULT NULL,
  `ocupacion` VARCHAR(35) NULL DEFAULT NULL,
  `profesion` VARCHAR(35) NULL DEFAULT NULL,
  `rh` VARCHAR(5) NULL DEFAULT NULL,
  `estrato` INT NULL DEFAULT NULL,
  `eps` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ndoc_tdoc_UNIQUE` (`ndoc` ASC) VISIBLE,
  INDEX `fk_tbl_persona_tbl_observaciones1` (`id_observacion` ASC) VISIBLE,
  INDEX `fk_personas_tipos_documentos1_idx` (`tdoc_persona` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_persona_tbl_observaciones1`
    FOREIGN KEY (`id_observacion`)
    REFERENCES `proyecto`.`observaciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_personas_tipos_documentos1`
    FOREIGN KEY (`tdoc_persona`)
    REFERENCES `proyecto`.`tipos_documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `proyecto`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`matriculas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion_matricula` VARCHAR(12) NOT NULL,
  `fecha_inicial` DATE NOT NULL,
  `fecha_final` DATE NULL DEFAULT NULL,
  `estado` TINYINT NOT NULL,
  `grado` VARCHAR(15) NULL DEFAULT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_matriculas_personas1` (`id_persona` ASC) VISIBLE,
  UNIQUE INDEX `matriculascol_UNIQUE` (`descripcion_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_matriculas_personas1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `proyecto`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `proyecto`.`cuotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`cuotas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mes` VARCHAR(15) NOT NULL,
  `valor` FLOAT NOT NULL,
  `saldo` FLOAT NOT NULL,
  `id_matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cuotas_matriculas1` (`id_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_cuotas_matriculas1`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `proyecto`.`matriculas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `proyecto`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consecutivo` VARCHAR(30) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `periodo_inicial` DATE NOT NULL,
  `periodo_final` DATE NOT NULL,
  `valor_cancelado` FLOAT NOT NULL,
  `rector` VARCHAR(30) NOT NULL,
  `id_cuota` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `consecutivo_UNIQUE` (`consecutivo` ASC) VISIBLE,
  INDEX `fk_pagos_cuotas1` (`id_cuota` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_cuotas1`
    FOREIGN KEY (`id_cuota`)
    REFERENCES `proyecto`.`cuotas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `proyecto`.`parentescos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`parentescos` (
  `parentesco` VARCHAR(35) NOT NULL,
  `id_estudiante` INT NOT NULL,
  `id_acudiente` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`, `id_acudiente`),
  INDEX `fk_parentescos_personas2` (`id_acudiente` ASC) VISIBLE,
  CONSTRAINT `fk_parentescos_personas1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `proyecto`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_parentescos_personas2`
    FOREIGN KEY (`id_acudiente`)
    REFERENCES `proyecto`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
